name: Xenial-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  industrial_ci:
    name: Xenial-Build
    runs-on: ubuntu-latest
    env:
      CI_NAME: Xenial-Build
      OS_NAME: ubuntu
      OS_CODE_NAME: xenial
      ROS_DISTRO: kinetic
      ROS_REPO: main
      UPSTREAM_WORKSPACE: 'dependencies.rosinstall'
      ROSDEP_SKIP_KEYS: 'libqt5sql5-mysql'
      DOCKER_IMAGE: 'rosindustrial/noether:kinetic'
      UPSTREAM_CMAKE_ARGS: '-DNURBS_FOUND=TRUE'
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{env}}
